import { useMemo, type ComponentProps } from "react";
import { DashboardChrome } from "../components/DashboardChrome";
import { DashboardContent } from "../components/DashboardContent";
import {
  DashboardPopups,
  loadCreateProjectPopupModule,
  loadSearchPopupModule,
  loadSettingsPopupModule,
} from "../components/DashboardPopups";
import { useDashboardPopupBindings } from "./useDashboardPopupBindings";
import { useDashboardSettingsData } from "./useDashboardSettingsData";
import type { DashboardActionLayer } from "./useDashboardActionLayer";
import type { DashboardDataLayer } from "./useDashboardDataLayer";
import type { ProjectData } from "../../types";
type DashboardViewBindings = {
  hasSnapshot: boolean;
  popupsProps: ComponentProps<typeof DashboardPopups>;
  chromeProps: ComponentProps<typeof DashboardChrome>;
  contentProps: ComponentProps<typeof DashboardContent>;
};
const EMPTY_PROJECTS: Record<string, ProjectData> = {};
export function useDashboardViewBindings(
  dataLayer: DashboardDataLayer,
  actionLayer: DashboardActionLayer,
): DashboardViewBindings {
  const {
    user,
    signOut,
    navigation,
    data,
    viewerFallback,
    canCreateWorkspace,
    workspaceActions,
  } = dataLayer;
  const {
    dashboardCommands,
    projectActions,
    mainContentFileActions,
    createMainContentProjectActions,
    baseMainContentNavigationActions,
    handleNavigateToArchiveProject,
  } = actionLayer;
  const {
    createProjectViewer,
    searchPopupOpenSettings,
    searchPopupHighlightNavigate,
    handleSearchIntent,
    handleCreateProjectIntent,
    handleSettingsIntent,
    handleSignOut,
  } = useDashboardPopupBindings({
    viewerIdentity: data.viewerIdentity,
    setPendingHighlight: navigation.setPendingHighlight,
    openSettings: dashboardCommands.settings.openSettings,
    preloadSearchPopupModule: loadSearchPopupModule,
    preloadCreateProjectPopupModule: loadCreateProjectPopupModule,
    preloadSettingsPopupModule: loadSettingsPopupModule,
    signOut,
  });
  const {
    settingsAccountData,
    settingsNotificationsData,
    settingsCompanyData,
  } = useDashboardSettingsData({
    accountSettings: data.accountSettings,
    notificationSettings: data.notificationSettings,
    companySummary: data.companySummary,
    companyMembersResult: data.companyMembersResult,
    companyPendingInvitationsResult: data.companyPendingInvitationsResult,
    companyBrandAssetsResult: data.companyBrandAssetsResult,
    fallbackAvatarUrl:
      data.viewerIdentity.avatarUrl ?? viewerFallback.avatarUrl,
    user,
  });
  const popupProjects = useMemo(
    () =>
      navigation.isSearchOpen ||
      navigation.isCreateProjectOpen ||
      navigation.isCompletedProjectsOpen
        ? data.projectsById
        : EMPTY_PROJECTS,
    [
      data.projectsById,
      navigation.isCompletedProjectsOpen,
      navigation.isCreateProjectOpen,
      navigation.isSearchOpen,
    ],
  );
  const popupsProps = useMemo<ComponentProps<typeof DashboardPopups>>(
    () => ({
      isSearchOpen: navigation.isSearchOpen,
      setIsSearchOpen: navigation.setIsSearchOpen,
      projects: popupProjects,
      workspaceTasks: data.workspaceTasks,
      tasksByProject: data.tasksByProject,
      allWorkspaceFiles: data.allWorkspaceFiles,
      workspaceFilesPaginationStatus: data.workspaceFilesPaginationStatus,
      loadMoreWorkspaceFiles: data.loadMoreWorkspaceFiles,
      navigateView: navigation.navigateView,
      openCreateProject: navigation.openCreateProject,
      searchPopupOpenSettings,
      searchPopupHighlightNavigate,
      isCreateProjectOpen: navigation.isCreateProjectOpen,
      closeCreateProject: navigation.closeCreateProject,
      dashboardCommands,
      createProjectViewer,
      editProjectId: navigation.editProjectId,
      editDraftData: navigation.editDraftData,
      reviewProject: navigation.reviewProject,
      handleUpdateComments: projectActions.handleUpdateComments,
      handleApproveReviewProject: projectActions.handleApproveReviewProject,
      isCreateWorkspaceOpen: navigation.isCreateWorkspaceOpen,
      closeCreateWorkspace: navigation.closeCreateWorkspace,
      handleCreateWorkspaceSubmit: workspaceActions.handleCreateWorkspaceSubmit,
      isCompletedProjectsOpen: navigation.isCompletedProjectsOpen,
      closeCompletedProjectsPopup: navigation.closeCompletedProjectsPopup,
      completedProjectDetailId: navigation.completedProjectDetailId,
      openCompletedProjectDetail: navigation.openCompletedProjectDetail,
      backToCompletedProjectsList: navigation.backToCompletedProjectsList,
      projectFilesByProject: data.projectFilesByProject,
      projectFilesPaginationStatus: data.projectFilesPaginationStatus,
      loadMoreProjectFiles: data.loadMoreProjectFiles,
      workspaceMembers: data.workspaceMembers,
      viewerIdentity: data.viewerIdentity,
      mainContentFileActions,
      createMainContentProjectActions,
      baseMainContentNavigationActions,
      isSettingsOpen: navigation.isSettingsOpen,
      settingsTab: navigation.settingsTab,
      activeWorkspace: data.activeWorkspace,
      settingsAccountData,
      settingsNotificationsData,
      settingsCompanyData,
      resolvedWorkspaceSlug: data.resolvedWorkspaceSlug,
      companySummary: data.companySummary,
      handleUpdateWorkspaceGeneral:
        workspaceActions.handleUpdateWorkspaceGeneral,
      handleUploadWorkspaceLogo: workspaceActions.handleUploadWorkspaceLogo,
      handleInviteWorkspaceMember: workspaceActions.handleInviteWorkspaceMember,
      handleChangeWorkspaceMemberRole:
        workspaceActions.handleChangeWorkspaceMemberRole,
      handleRemoveWorkspaceMember: workspaceActions.handleRemoveWorkspaceMember,
      handleResendWorkspaceInvitation:
        workspaceActions.handleResendWorkspaceInvitation,
      handleRevokeWorkspaceInvitation:
        workspaceActions.handleRevokeWorkspaceInvitation,
      handleUploadWorkspaceBrandAsset:
        workspaceActions.handleUploadWorkspaceBrandAsset,
      handleRemoveWorkspaceBrandAsset:
        workspaceActions.handleRemoveWorkspaceBrandAsset,
      handleGetWorkspaceBrandAssetDownloadUrl:
        workspaceActions.handleGetWorkspaceBrandAssetDownloadUrl,
      handleSoftDeleteWorkspace: workspaceActions.handleSoftDeleteWorkspace,
    }),
    [
      createProjectViewer,
      dashboardCommands,
      data.activeWorkspace,
      data.allWorkspaceFiles,
      data.loadMoreWorkspaceFiles,
      data.companySummary,
      data.tasksByProject,
      popupProjects,
      data.projectFilesByProject,
      data.projectFilesPaginationStatus,
      data.resolvedWorkspaceSlug,
      data.workspaceFilesPaginationStatus,
      data.loadMoreProjectFiles,
      data.workspaceMembers,
      data.workspaceTasks,
      data.viewerIdentity,
      navigation.closeCreateProject,
      navigation.closeCreateWorkspace,
      navigation.closeCompletedProjectsPopup,
      navigation.completedProjectDetailId,
      navigation.backToCompletedProjectsList,
      navigation.editDraftData,
      navigation.editProjectId,
      navigation.isCompletedProjectsOpen,
      navigation.isCreateProjectOpen,
      navigation.isCreateWorkspaceOpen,
      navigation.isSearchOpen,
      navigation.isSettingsOpen,
      navigation.navigateView,
      navigation.openCompletedProjectDetail,
      navigation.openCreateProject,
      navigation.reviewProject,
      navigation.setIsSearchOpen,
      navigation.settingsTab,
      baseMainContentNavigationActions,
      createMainContentProjectActions,
      mainContentFileActions,
      projectActions.handleApproveReviewProject,
      projectActions.handleUpdateComments,
      searchPopupHighlightNavigate,
      searchPopupOpenSettings,
      settingsAccountData,
      settingsCompanyData,
      settingsNotificationsData,
      workspaceActions.handleChangeWorkspaceMemberRole,
      workspaceActions.handleCreateWorkspaceSubmit,
      workspaceActions.handleInviteWorkspaceMember,
      workspaceActions.handleRemoveWorkspaceBrandAsset,
      workspaceActions.handleRemoveWorkspaceMember,
      workspaceActions.handleGetWorkspaceBrandAssetDownloadUrl,
      workspaceActions.handleResendWorkspaceInvitation,
      workspaceActions.handleRevokeWorkspaceInvitation,
      workspaceActions.handleSoftDeleteWorkspace,
      workspaceActions.handleUpdateWorkspaceGeneral,
      workspaceActions.handleUploadWorkspaceBrandAsset,
      workspaceActions.handleUploadWorkspaceLogo,
    ],
  );
  const chromeProps = useMemo<ComponentProps<typeof DashboardChrome>>(
    () => ({
      isSidebarOpen: navigation.isSidebarOpen,
      navigateView: navigation.navigateView,
      openSearch: navigation.openSearch,
      handleSearchIntent,
      currentView: navigation.currentView,
      openCreateProject: navigation.openCreateProject,
      handleCreateProjectIntent,
      visibleProjects: data.sidebarVisibleProjects,
      viewerIdentity: data.viewerIdentity,
      activeWorkspace: data.activeWorkspace,
      workspaces: data.workspaces,
      canCreateWorkspace,
      handleSettingsIntent,
      handleSignOut,
      onSwitchWorkspace: dashboardCommands.workspace.switchWorkspace,
      onCreateWorkspace: dashboardCommands.workspace.createWorkspace,
      onOpenSettings: dashboardCommands.settings.openSettings,
      onEditProject: dashboardCommands.project.editProject,
      onViewReviewProject: dashboardCommands.project.viewReviewProject,
      onOpenCompletedProjectsPopup: navigation.openCompletedProjectsPopup,
    }),
    [
      canCreateWorkspace,
      dashboardCommands.project.editProject,
      dashboardCommands.project.viewReviewProject,
      dashboardCommands.settings.openSettings,
      dashboardCommands.workspace.createWorkspace,
      dashboardCommands.workspace.switchWorkspace,
      data.activeWorkspace,
      data.viewerIdentity,
      data.sidebarVisibleProjects,
      data.workspaces,
      handleCreateProjectIntent,
      handleSearchIntent,
      handleSettingsIntent,
      handleSignOut,
      navigation.currentView,
      navigation.isSidebarOpen,
      navigation.navigateView,
      navigation.openCompletedProjectsPopup,
      navigation.openCreateProject,
      navigation.openSearch,
    ],
  );
  const contentProps = useMemo<ComponentProps<typeof DashboardContent>>(
    () => ({
      contentModel: data.contentModel,
      handleToggleSidebar: data.handleToggleSidebar,
      isSidebarOpen: navigation.isSidebarOpen,
      visibleProjects: data.visibleProjects,
      tasksByProject: data.tasksByProject,
      workspaceTasks: data.workspaceTasks,
      workspaceActivities: data.workspaceActivities,
      tasksPaginationStatus: data.tasksPaginationStatus,
      loadMoreWorkspaceTasks: data.loadMoreWorkspaceTasks,
      activitiesPaginationStatus: data.activitiesPaginationStatus,
      loadMoreWorkspaceActivities: data.loadMoreWorkspaceActivities,
      handleReplaceWorkspaceTasks: projectActions.handleReplaceWorkspaceTasks,
      workspaceMembers: data.workspaceMembers,
      viewerIdentity: data.viewerIdentity,
      handleNavigateToArchiveProject,
      handleUnarchiveProject: projectActions.handleUnarchiveProject,
      handleDeleteProject: projectActions.handleDeleteProject,
      highlightedArchiveProjectId: navigation.highlightedArchiveProjectId,
      setHighlightedArchiveProjectId: navigation.setHighlightedArchiveProjectId,
      projectFilesByProject: data.projectFilesByProject,
      projectFilesPaginationStatus: data.projectFilesPaginationStatus,
      loadMoreProjectFiles: data.loadMoreProjectFiles,
      mainContentFileActions,
      createMainContentProjectActions,
      baseMainContentNavigationActions,
      pendingHighlight: navigation.pendingHighlight,
      clearPendingHighlight: data.clearPendingHighlight,
      openCreateProject: navigation.openCreateProject,
    }),
    [
      baseMainContentNavigationActions,
      createMainContentProjectActions,
      data.clearPendingHighlight,
      data.contentModel,
      data.handleToggleSidebar,
      data.tasksByProject,
      data.projectFilesByProject,
      data.projectFilesPaginationStatus,
      data.loadMoreProjectFiles,
      data.workspaceActivities,
      data.tasksPaginationStatus,
      data.loadMoreWorkspaceTasks,
      data.activitiesPaginationStatus,
      data.loadMoreWorkspaceActivities,
      data.viewerIdentity,
      data.visibleProjects,
      data.workspaceMembers,
      data.workspaceTasks,
      handleNavigateToArchiveProject,
      mainContentFileActions,
      navigation.highlightedArchiveProjectId,
      navigation.isSidebarOpen,
      navigation.openCreateProject,
      navigation.pendingHighlight,
      navigation.setHighlightedArchiveProjectId,
      projectActions.handleDeleteProject,
      projectActions.handleReplaceWorkspaceTasks,
      projectActions.handleUnarchiveProject,
    ],
  );
  return {
    hasSnapshot: Boolean(data.snapshot),
    popupsProps,
    chromeProps,
    contentProps,
  };
}
